apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cactus-back-svc
  name: cactus-back-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cactus-back
  type: NodePort
status:
  loadBalancer: {}
