apiVersion: v1
kind: Service
metadata:
  labels:
    app: cactus-back-svc
  name: cactus-back-svc
spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 8081
   selector:
     app: cactus-back
   type: LoadBalancer


