apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cactus-front-svc
  name: cactus-front-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cactus-front
  type: NodePort
status:
  loadBalancer: {}
