apiVersion: v1
kind: Service
metadata:
  labels:
    app: cactus-redis-svc
  name: cactus-redis-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: cactus-redis
